---
- name: basic vm config
  hosts: vm1
  become: True
  remote_user: root
  tasks:
  - import_role:
      name: basic_config


- name: prerequisites setup
  hosts: vm1
  become: True
  remote_user: root
  tasks:
  - import_role:
      name: prerequisites


- name: installation
  hosts: vm1
  become: True
  remote_user: root
  tasks:
  - import_role:
      name: install


- name: configuration
  hosts: vm1
  become: True
  remote_user: root
  tasks:
  - import_role:
      name: config 
      
