---
- name: basic vm config
  hosts: vm1
  become: True
  remote_user: root
  tasks:
  - import_role:
      name: basic_config
    #when: apply_basic_config == 'true'

- name: prerequisites setup
  hosts: vm1
  become: True
  remote_user: root
  tasks:
  - import_role:
      name: prerequisites
    when: apply_prerequisites == 'true'

- name: installation
  hosts: vm1
  become: True
  remote_user: root
  tasks:
  - import_role:
      name: install
    when: allow_install=='true'

- name: configuration
  hosts: vm1
  become: True
  remote_user: root
  tasks:
  - import_role:
      name: config 
    when: allow_config=='true'
