---

- name: Install redis
  apt: name=redis-server state=present update_cache=yes

- name: Configure redis to allow external connections
  template: src=redis.conf dest=/etc/redis/redis.conf
  notify: redis-server restart

# install mysql
- name: Install MySQL packages
  apt:
    name: "{{ packages }}"
    state: present
  vars:
    packages:
      - mysql-common
      - mysql-server
      - mysql-client
  
- name: Install MySQL pip packages
  pip:
    name: "{{ packages }}"
    state: present
  vars:
    packages:
      #- MySQL-python
      - PyMySQL
      
- name: Enable the MySQL service
  service:
    name: mysql
    state: started
    enabled: true